### ISSUE TITLE
Assignment 01

### ISSUE THREAD

**Issue by sgpratik** [Priya-661/Python_basics#1]
1. Write a Python program that prints "Hello, World!" to the console.

2. Write a program that takes two numbers as input from the user and prints their sum.

3. Write a program that takes an integer input from the user and prints whether it is even or odd.

4. Write a program that converts temperature from Celsius to Fahrenheit. Ask the user for the temperature in Celsius and print the equivalent temperature in Fahrenheit.

5. Write a program to calculate the factorial of a number. Ask the user for an integer input and print its factorial.

**Comment by sgpratik** [comment]
Create a branch push code into it and raise a PR.

**Comment by Priya-661** [comment]
Done, Please check!

**Comment by sgpratik** [comment]
Please redo the tasks 4th and 5th.

**Comment by Priya-661** [comment]
Tasks 4 & 5 modified, Please check and verify.
