### ISSUE TITLE
Python and SQL Assignment #2

### ISSUE THREAD

**Issue by sgpratik** [Priya-661/Python_basics#10]
Use Python to execute the following advanced SQL tasks. Write the necessary Python code and SQL queries for each question. Ensure you handle exceptions and establish a connection to your MySQL database correctly.

Create a new table named courses with the following columns:

course_id (integer and primary key)
course_name (varchar)
description (text)
credits (integer)

Insert three records into the courses table with the following values:

(1, 'Mathematics', 'A course on basic mathematics', 3)
(2, 'Physics', 'An introductory course to physics', 4)
(3, 'Chemistry', 'Fundamentals of chemistry', 4)
DQL: Write a query to fetch all records from the courses table and display them in a tabular format using Python.

Add a new column semester (integer) to the courses table and set a default value of 1 for all existing records.

Update the credits of the course with course_id 2 to 5.

Write a query to fetch the course_name and credits of courses that have more than 3 credits.

Remove the description column from the courses table.

Delete the record of the course with course_id 3.

Write a query to count the total number of courses in the courses table.

Rename the courses table to subjects.

Write a Python script to insert multiple records into the subjects table with values provided by the user at runtime.

**Comment by Satyamani89** [comment]
@Priya-661 Please try to update the status of the ticket regularly as a best practice

**Comment by Priya-661** [comment]
Hi Pratik, I have a question about Python dotenv. How do we use it, and how can we connect the session once at a time? I've been working on it, so please give me this day to look into it. I'll resolve this ticket soon.

**Comment by sgpratik** [comment]
@Priya-661, can you also upload the requirements.txt file? I want to know what the dependencies that you have installed.  You don't have to create one session. You need to create a new session for every transaction that you do. Check this link out, https://realpython.com/python-mysql/

**Comment by sgpratik** [comment]
You need to make your session maker centralised and not write the same code again. That makes it redundant.
