### ISSUE TITLE
Assignment : Week 2

### ISSUE THREAD

**Issue by sgpratik** [Priya-661/Python_basics#3]
1: Write a Python function that takes a list of integers as input and returns the sum of all the integers in the list.

2: Write a Python function that takes a string as input and returns the number of vowels (a, e, i, o, u) present in the string. 

3: Write a Python function that takes a list of strings as input and returns the longest string in the list. 

4: Write a Python function that takes a dictionary as input and returns a list containing the keys of the dictionary sorted in ascending order. 

5: Write a Python function that takes two sets as input and returns a new set containing the common elements present in both sets.

**Comment by Priya-661** [comment]
Thank you for your response.
